// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://myqjitezxfqxcoqmycgk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im15cWppdGV6eGZxeGNvcW15Y2drIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyMjUzOTEsImV4cCI6MjA2NzgwMTM5MX0.O3Ayc9DePD_HVYV24JMgtJh1NUlXD_cMc9_8OAeVkQQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);